export class Icon {
}

export type IconName = 
'clock-plus'|
'label-hd'|
'cross'|
'cut'|
'chevrons-up'|
'emotion-happy'|
'minimize'|
'trend-up'|
'send'|
'checkbox-square'|
'checkbox-square-outline'|
'airplay'|
'forward-15'|
'comment-2-question'|
'alert-octangle'|
'box-2'|
'clock-check'|
'play'|
'loader-2'|
'preventative-health'|
'file-minus'|
'folder-check'|
'webcam'|
'wrench'|
'check'|
'speed'|
'infinity'|
'comment'|
'arrow-top-left'|
'dashboard'|
'clock-slash'|
'anchor'|
'maximize-2-1'|
'file'|
'refresh-ccw'|
'calendar-arrow-right'|
'rocket-2'|
'file-cross'|
'comment-2-check'|
'chevron-down'|
'user-minus'|
'stop'|
'export'|
'brush'|
'radio-filled'|
'presentation-chart'|
'toggle-off'|
'chevrons-left'|
'battery-3'|
'trophy'|
'award'|
'rocket'|
'cross-circle'|
'playlist'|
'folder-plus'|
'comment-2-minus'|
'history'|
'label-hq'|
'briefcase-2'|
'bed'|
'redo-2'|
'keyboard-show'|
'terminal'|
'maximize-1'|
'activity'|
'fast-forward'|
'gift'|
'invoice'|
'user-alert'|
'shopping-basket'|
'emotion-smile'|
'filter-2'|
'radio1'|
'note-text'|
'sliders-vert'|
'external-link-2'|
'log-out'|
'undo-2'|
'heart'|
'heart-filled'|
'zoom-in'|
'globe'|
'comment-2-plus'|
'filter'|
'arrow-bottom-right'|
'women-men-health'|
'nut'|
'diskette'|
'volume-low'|
'headphones-2'|
'calendar-plus'|
'clock-minus'|
'film-board'|
'comment-2-slash'|
'arrow-left-circle'|
'volume-cross'|
'sliders-horiz-2'|
'arrow-top-right-circle'|
'sign-in'|
'dashboard-2'|
'sign-out'|
'thumbs-up'|
'replay'|
'sticker'|
'forward-5'|
'copyright'|
'fitness'|
'bookmarks'|
'zoom-out'|
'folder-compressed'|
'more-horiz'|
'folder'|
'calendar-minus'|
'arrow-bottom-circle'|
'import'|
'gear-2'|
'user-square'|
'ticket'|
'cast'|
'speaker'|
'folder-upload'|
'play-previous'|
'arrow-top-left-circle'|
'time'|
'arrows-move'|
'stop-circle'|
'arrow-bottom-left-circle'|
'forward-10'|
'modules'|
'timer'|
'reply'|
'redo'|
'battery-2'|
'gear'|
'weighter'|
'scale'|
'clipboard-cross'|
'bluetooth'|
'glasses-vr'|
'pin-cross'|
'forward-all'|
'chevrons-down'|
'film-reel'|
'book-library'|
'memory-card'|
'sleep'|
'emotion-neutral'|
'film-tape'|
'flag'|
'copy'|
'newspaper'|
'label-explicit'|
'note-2'|
'folder-heart'|
'users'|
'globe-2'|
'clipboard-slash'|
'box'|
'monitor'|
'calendar-person'|
'activity-2'|
'gps-slash'|
'playlist-play'|
'equalizer'|
'music-library'|
'bookmark-plus'|
'user-check'|
'arrow-corner-cw-rb'|
'comment-minus'|
'bookmark'|
'weighter-2'|
'comment-plus'|
'minus-circle'|
'log-in'|
'replay-10'|
'comment-2-dots'|
'arrow-corner-ccw-lt'|
'arrows-expand'|
'comment-2'|
'stopwatch'|
'folder-open'|
'play-slowmotion'|
'arrow-right'|
'video-queue'|
'comment-2-alert'|
'wifi'|
'user-arrow-bottom'|
'presentation-line'|
'file-draft'|
'comment-2-cancel'|
'fast-rewind'|
'replay-5'|
'user-arrow-top'|
'notification-identifier'|
'pin-plus'|
'book-open'|
'note-2-text'|
'compass'|
'notebook'|
'pin'|
'checkbox-filled'|
'arrow-left-curved-circle'|
'comment-dots'|
'folder-move'|
'bulb'|
'arrow-top'|
'flag-2'|
'battery-slash'|
'battery-1'|
'arrow-right-circle'|
'emotion-sad'|
'keyboard-hide'|
'bell-minus'|
'laptop'|
'sort-text-reverse'|
'comments-2'|
'file-upload'|
'music-note-2'|
'folder-music'|
'arrow-corner-cw-lb'|
'repeat'|
'calendar-event'|
'games'|
'file-text'|
'calendar'|
'check-circle'|
'bulb-slash'|
'sort-number'|
'captions-1'|
'share'|
'clock-zzz'|
'music-note-3'|
'umbrella'|
'volume-mute'|
'maximize-2'|
'mic-slash'|
'repeat-on'|
'minus-octangle'|
'toggle-on'|
'trend-down'|
'chevrons-right'|
'email'|
'folder-download'|
'star-slash'|
'file-invoice'|
'arrow-corner-cw-rt'|
'clipboard-text'|
'comment-alert'|
'webcam-slash'|
'fire'|
'file-download'|
'dumbell'|
'refresh-cw'|
'maximize1'|
'inbox-out'|
'comment-check'|
'tablet'|
'tags'|
'calendar-cross'|
'bed-1'|
'loader'|
'pin-check'|
'comment-cancel'|
'target'|
'map-view'|
'shopping-bag-2'|
'file-heart'|
'chevron-right'|
'video-camera-slash'|
'bookmark-minus'|
'emails'|
'user-arrow-tr'|
'crosshair'|
'calendar-number'|
'user-cross'|
'bookmark-slash'|
'user'|
'planet'|
'user-plus'|
'rotate-cw'|
'flag-3'|
'video-plus'|
'tag-2'|
'user-arrow-bl'|
'radio'|
'pause-circle'|
'cross-octangle'|
'hard-drive'|
'arrow-right-curved-circle'|
'loading-trolley'|
'bell-slash'|
'arrow-corner-ccw-lb'|
'cd'|
'pin-slash'|
'comment-text'|
'baby-carriage'|
'plus'|
'external-link'|
'weight'|
'mouse'|
'tag'|
'tv'|
'music-queue'|
'more-vert'|
'watch-2'|
'trash'|
'note'|
'clock-cross'|
'book-plus'|
'music-note'|
'file-agreement'|
'mic'|
'volume-high'|
'arrow-bottom-left'|
'alert-triangle'|
'calendar-dates'|
'file-check'|
'delay-aging'|
'folder-minus'|
'bell-plus'|
'arrow-corner-cw-lt'|
'captions'|
'headphones'|
'play-next'|
'question'|
'atom'|
'gps'|
'file-scan'|
'clipboard-minus'|
'flashcard'|
'wheelchair'|
'minus'|
'arrows-expand-2'|
'arrow-top-right'|
'user-arrow-right'|
'pin-minus'|
'bell-check'|
'bookmark-check'|
'watch'|
'arrow-left'|
'arrow-top-circle'|
'comments'|
'replay-15'|
'play-circle'|
'book-queue'|
'lifebuoy'|
'receipt'|
'volume-slash'|
'pin-2'|
'broadcast'|
'truck'|
'thermometer'|
'megaphone'|
'forward'|
'checkbox'|
'bed-2'|
'hashtag-circle'|
'tags-2'|
'sliders-horiz'|
'import-2'|
'processor'|
'folder-cross'|
'new-release'|
'at'|
'arrow-corner-ccw-rb'|
'user-circle'|
'calendar-note'|
'refresh-ccw-alert'|
'archive'|
'shopping-cart-2'|
'plug-slash'|
'alert-circle'|
'menu'|
'comment-slash'|
'chevron-up'|
'heart-slash'|
'stopwatch-slash'|
'route'|
'music-plus'|
'pain-management'|
'file-move'|
'plus-circle'|
'arrows-move-2'|
'thumbs-down'|
'swatchbook'|
'home'|
'inbox-in'|
'barchart'|
'reply-all'|
'export-2'|
'chevron-left'|
'search'|
'maximize'|
'battery'|
'trash-2'|
'arrow-corner-ccw-rt'|
'sort-number-reverse'|
'pin-3'|
'power'|
'devices'|
'export-3'|
'import-3'|
'video-camera'|
'direction'|
'rotate-ccw'|
'briefcase-doctor'|
'degrees'|
'plug'|
'send-2'|
'battery-charging'|
'hashtag'|
'verified'|
'bell'|
'file-slash'|
'checkbox-circle'|
'folder-photo'|
'emotion-wow'|
'folder-cloud'|
'plus-square'|
'book'|
'label-4k'|
'layers'|
'video-library'|
'file-code'|
'refresh-cw-alert'|
'glasses'|
'folder-slash'|
'arrow-bottom'|
'slash'|
'keyboard'|
'pause'|
'comment-2-text'|
'brackets'|
'immune-system'|
'inbox'|
'briefcase'|
'direction-2'|
'undo'|
'sliders-vert-2'|
'clipboard-plus'|
'clock'|
'code'|
'inbox-filled'|
'sort-text'|
'clipboard-check'|
'timer-2'|
'shopping-bag'|
'shopping-cart'|
'file-plus'|
'arrow-swap'|
'miniplayer'|
'arrow-bottom-right-circle'|
'yin-yang'|
'record'|
'comment-2-info'|
'smartphone'|
'info'|
'file-shredder'|
'wifi-slash'|
'nutritutan'|
'clipboard'|
'star'